[google_sheets]
CELULAS_ID = "1GEtYGIQCucTTd6yVuC7dssMuJeYklbehJfWAC1UNkpE"
FILE_NAME = "celulas"
SHEET_CELULAS = "celulas"
SHEET_DISCIPULADOS = "discipulados"
SHEET_CODIGOS = "codigos"
SHEET_LIDERAZGO = "liderazgo"
SHEET_LIDERAZGO_X_CODIGO = "liderazgo_x_codigo"
SHEET_REDES = "redes"
SHEET_HIST_CELULAS = "hist_celulas"
SHEET_HIST_DISCUPULADOS = "hist_discipulados"
SHEET_TEMAS = "temas"

[google_service_account]
type = "service_account"
project_id = "python-sheet-tesel-453121"
private_key_id = "654be65e1321c2a4c3b8841fc8fd4b3e21ade4fa"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC5cC7uuuXdxwuQ\nXlCl/suiw6u7oWouaQfDUgViltj2E8lX3qz97OscYunwTd9xQC1pQPE4zy+fpBWI\nOtdHcrcek52IZlTBv7WTJNnCwi0N1HhFnvsAlchBh6lipJo5OkU4LZc0pqQ2GaL6\nXlqTovzCzAyGQ0ttXFznl1ZaoHKW0snu14KLG+MQTfaBC6wbwOdfKvJKLOomdYBk\nDiGIJUZ9j9XOZyM65Nc9xdE2lQOfJ3pHAGEQNfIMjoNL/8MhD2yekURsNPM90k3S\nspv81/t07KjKZEJJTeX30Xl5ujFb49gO1NtMrbvSJx1YjzyvoBXvA1yZ8o2W9IhB\nyXz79X3jAgMBAAECggEAA07F94or6X3Qbf3QsHVQCpI08P7bFwLWmZxP7kdEjXci\n40dcjJb6RqJZC+lHsAx2AueepeXEMrPJkomCJ4sbSxdU+wbgQih6Q6qnm7q89P8y\nOgOw9Hy3ervBwLmw6o5oh60AgnbqfPCOIKsoMHP60Dq1inuOz9+S5KqlZq5v/NKz\n4GtOIbmylrB9bOTfZf23m11ojozeEAshDSDNIP+6VIPp/GZDYGRNBJwYeOTWfMAq\naeUIBtNjinPKJgg1d054eqloA/+mzXCxeL1UfS71N+Tjb7rWGfdZBYGAj8LFWrZ0\nzE8ejPZvajB7P7YBjFUhvOkwsx4Jg3JID72Pq0oNEQKBgQD6QAqkVbrXuSJmTH0i\nA9KyqwMAp9SGClA3SiMyxpb3V9Z090ySqkY6NTbV9av2p1bcEiMnp2oqWpHZZ1fn\nrIaQr9pR2hTKa4eQ345BEZ/sjtYj+8yxVtUg8UMtpWj+bHu4u7dTJvse+l5CukkR\ns4p3914X4OIkRY2IBQEE9/WA6wKBgQC9suvYEfCiI+i+/DYA0PPEyBSwml5jePSm\nHaw+uzyNubVTodWhuMP4l1DFKklSsniMPG5up8Y5muurdxUGQ7as0g1M7NxQ4Gry\n8hcqaNJbzAE0TVPvYBZyD2t2QYVLIyFGy1v5kQGV6twHeB0o8IxLZghWZM9zuT+w\nvTG2rf946QKBgBT/aKUvWFUfgKZqxpkjDvvU45SbgHaayO5KtzdceHBam3EHCxLH\nXMsnielcCsjQc7ZVg0OhhYP2Q4SlajfTPxtG1h/GF7aAXUinqW0GSI/10DwGtb8v\nlQSFmehrl6q5eYwfnBtLCwknYt9geB8XHIhCZk/Em9UFTQHbwaEkGSJvAoGAdvHq\naagOD0ye0qoIHojmYLvoJTgV+R9Nn585cngqpt8L8G2oK2hUENqoPYifQyg+6Ae4\nYs/2PgaCwRfA6hWpREHNLy/RkTC2PrFHj0L8q6yGEMpv18eTK1+5zQOWVZ+obOB0\nQk8HBH6oClLpTdNO1LQchDdf0LsWUXa/5kDB0IkCgYB/bExDTjqc/l7eqDPDXKHt\nM1i71C9lXvXJu6Xh19JFo5j/GOczcNBbTOfDCoLXlZ/khwpTEtabUPcyqrLAEEUd\nBNTMEOlQ0JLkn/3ooOizCZ57N8Xk63gMWoQmlCQ04ck+PXK9jBkgmws4LnVu2KMP\nPQZqopdrjvjLo8XtW0L/Mw==\n-----END PRIVATE KEY-----\n"
client_email = "celulas@python-sheet-tesel-453121.iam.gserviceaccount.com"
client_id = "100698671650867794349"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/celulas%40python-sheet-tesel-453121.iam.gserviceaccount.com"
universe_domain = "googleapis.com"